[functions]
  directory = "functions"
  node_bundler = "esbuild"

[build]
  command = "npm run build" # or whatever your build command is
  publish = "public" # You need a public directory for Netlify, even if empty

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200