[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["public/**/*.ejs"]